# Generated by Django 2.0.2 on 2018-02-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fiestaevento',
            name='Fotos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Domain.Fotos'),
        ),
        migrations.AlterField(
            model_name='fiestaevento',
            name='Lugar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Domain.Lugar'),
        ),
    ]
