# Generated by Django 2.0.2 on 2018-03-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta1', '0002_auto_20180226_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentocarrito',
            name='FiestaEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fiesta1.FiestaEvento'),
        ),
    ]
