# Generated by Django 2.0.2 on 2018-02-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boda',
            name='Enamorado1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enamorado1', to='Pareja.Enamorado'),
        ),
        migrations.AlterField(
            model_name='boda',
            name='Enamorado2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enamorado2', to='Pareja.Enamorado'),
        ),
        migrations.AlterField(
            model_name='decoracion',
            name='descripcion',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='decoracion',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='decoracion',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='descripcion',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='tipo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
