# Generated by Django 2.0.4 on 2018-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta', '0005_auto_20180504_1421'),
        ('Ceremonia', '0002_auto_20180504_1421'),
        ('Domain', '0002_auto_20180427_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fotos',
        ),
        migrations.AlterField(
            model_name='boda',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
    ]
