# Generated by Django 2.0.4 on 2018-05-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0003_auto_20180504_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ceremonia', 'Ceremonia'), ('fiesta', 'Fiesta')], default=None, max_length=50),
        ),
    ]
