# Generated by Django 2.0.4 on 2018-05-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0004_lugar_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(choices=[('ceremonia', 'Ceremonia'), ('fiesta', 'Fiesta')], max_length=50),
        ),
    ]
