# Generated by Django 2.0.4 on 2018-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lunamielevento',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
    ]
