# Generated by Django 2.0.2 on 2018-02-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMiel', '0002_auto_20180226_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
