# Generated by Django 2.0.4 on 2018-05-14 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMiel', '0002_auto_20180513_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='cantidad',
        ),
    ]
