# Generated by Django 2.0.4 on 2018-05-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMiel', '0002_auto_20180513_1800'),
        ('LunaMiel', '0003_auto_20180513_2003'),
    ]

    operations = [
    ]
