# Generated by Django 2.0.4 on 2018-05-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMiel', '0004_merge_20180514_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='LunaMiel/Actividad'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='LunaMiel/Hotel'),
        ),
    ]
