# Generated by Django 2.0.4 on 2018-05-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Fiesta/Alimento'),
        ),
        migrations.AlterField(
            model_name='decoracionfiesta',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Fiesta/Decoracion'),
        ),
        migrations.AlterField(
            model_name='entretenimiento',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Fiesta/Entretenimiento'),
        ),
    ]
