# Generated by Django 2.0.4 on 2018-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentocarrito',
            name='Cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
