# Generated by Django 2.0.4 on 2018-04-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentocarrito',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='decoracionfiesta',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entretenimiento',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fiestaevento',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
    ]
