# Generated by Django 2.0.4 on 2018-05-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta', '0002_auto_20180519_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='imagen',
            field=models.ImageField(default='', upload_to='Fiesta/Alimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decoracionfiesta',
            name='imagen',
            field=models.ImageField(default='', upload_to='Fiesta/Decoracion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entretenimiento',
            name='imagen',
            field=models.ImageField(default='', upload_to='Fiesta/Entretenimiento'),
            preserve_default=False,
        ),
    ]
