# Generated by Django 2.0.4 on 2018-04-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta', '0003_auto_20180427_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiestaevento',
            name='Lugar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Domain.Lugar'),
        ),
    ]
