# Generated by Django 2.0.4 on 2018-05-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta', '0005_auto_20180504_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentocarrito',
            name='subtotal',
            field=models.BigIntegerField(default=0),
        ),
    ]
