# Generated by Django 2.0.4 on 2018-05-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta', '0006_alimentocarrito_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Fiesta/Alimentos'),
        ),
        migrations.AlterField(
            model_name='decoracionfiesta',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Fiesta/Decoraciones'),
        ),
        migrations.AlterField(
            model_name='entretenimiento',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Fiesta/Entretenimientos'),
        ),
    ]
