# Generated by Django 2.0.4 on 2018-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ceremonia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremoniaevento',
            name='Fotos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ceremoniaevento',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='decoracionceremonia',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ministro',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='musica',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
    ]
