# Generated by Django 2.0.2 on 2018-02-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ceremonia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremoniaevento',
            name='Fotos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Domain.Fotos'),
        ),
        migrations.AlterField(
            model_name='ceremoniaevento',
            name='Lugar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Domain.Lugar'),
        ),
        migrations.AlterField(
            model_name='ceremoniaevento',
            name='Ministro',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ceremonia.Ministro'),
        ),
        migrations.AlterField(
            model_name='ceremoniaevento',
            name='Musica',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ceremonia.Musica'),
        ),
        migrations.AlterField(
            model_name='ministro',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='musica',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
