# Generated by Django 2.0.4 on 2018-05-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ceremonia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoracionceremonia',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Ceremonia/Decoracion'),
        ),
        migrations.AlterField(
            model_name='ministro',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Ceremonia/Ministros'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Ceremonia/Musicas'),
        ),
    ]
