# Generated by Django 2.0.4 on 2018-05-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ceremonia', '0002_auto_20180519_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoracionceremonia',
            name='imagen',
            field=models.ImageField(default='', upload_to='Ceremonia/Decoracion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ministro',
            name='imagen',
            field=models.ImageField(default='', upload_to='Ceremonia/Ministro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musica',
            name='imagen',
            field=models.ImageField(default='', upload_to='Ceremonia/Musica'),
            preserve_default=False,
        ),
    ]
