# Generated by Django 2.0.4 on 2018-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pareja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='belleza',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enamorado',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
    ]
