# Generated by Django 2.0.2 on 2018-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pareja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enamorado',
            name='telefono',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
