# Generated by Django 2.0.4 on 2018-05-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pareja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Pareja/Accesorio'),
        ),
        migrations.AlterField(
            model_name='belleza',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Pareja/Belleza'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Pareja/Prenda'),
        ),
    ]
