# Generated by Django 2.0.3 on 2018-05-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pareja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='tipo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixta')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='belleza',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enamorado',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
    ]
