# Generated by Django 2.0.2 on 2018-02-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pareja', '0003_auto_20180226_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enamorado',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
