# Generated by Django 2.0.4 on 2018-05-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pareja', '0003_auto_20180513_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belleza',
            name='maquillaje',
            field=models.CharField(default='algo', max_length=250),
            preserve_default=False,
        ),
    ]
