# Generated by Django 2.0.4 on 2018-05-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pareja', '0004_auto_20180513_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='talla',
            field=models.CharField(max_length=250),
        ),
    ]
