# Generated by Django 2.0.2 on 2018-03-15 12:29

import Pareja.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pareja', '0005_auto_20180226_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enamorado',
            name='cedula',
            field=models.CharField(max_length=50, validators=[Pareja.models.numeric_validator]),
        ),
    ]
