# Generated by Django 2.0.2 on 2018-02-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiesta2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretenimiento',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
